# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-06-16 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_alter_request_method_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='query_string',
            field=models.CharField(verbose_name='query string', max_length=255, blank=True),
        ),
    ]
